version: "3"
services:
  localai:
    image: localai/localai:latest
    ports:
      - 8080:8080
    volumes:
      - ./models:/models
      - ./models.yaml:/models.yaml
      - ./config.yaml:/config.yaml
